In [1]:
from PIL import Image
import numpy as np

In [2]:
img = Image.open("Aeroplane.png")
image_array = np.array(img)

In [3]:
print(image_array)

[[[ 76 115 180]
  [ 74 113 178]
  [ 74 113 178]
  ...
  [ 78 116 179]
  [ 82 117 181]
  [ 84 118 182]]

 [[ 74 113 178]
  [ 74 113 178]
  [ 75 114 179]
  ...
  [ 78 116 179]
  [ 82 117 181]
  [ 82 116 180]]

 [[ 75 114 179]
  [ 73 112 177]
  [ 74 113 178]
  ...
  [ 80 117 180]
  [ 80 115 179]
  [ 80 116 179]]

 ...

 [[ 72 114 177]
  [ 73 116 178]
  [ 74 115 179]
  ...
  [ 79 118 180]
  [ 79 120 182]
  [ 79 119 181]]

 [[ 74 115 177]
  [ 75 116 178]
  [ 73 114 178]
  ...
  [ 83 120 184]
  [ 78 117 180]
  [ 78 118 180]]

 [[ 75 116 178]
  [ 74 115 177]
  [ 74 115 179]
  ...
  [ 79 117 180]
  [ 78 118 180]
  [ 81 121 183]]]


In [10]:
# Function to flip the image horizontally
def flip_horizontal(img_array):
    return np.flip(img_array, axis=1)

# Function to flip the image vertically
def flip_vertical(img_array):
    return np.flip(img_array, axis=0)

# Flip the image horizontally and vertically
flipped_horizontal = flip_horizontal(image_array)
flipped_vertical = flip_vertical(image_array)

# Save the flipped images
output_file_horizontal = 'output_horizontal.png'
output_file_vertical = 'output_vertical.png'

Image.fromarray(flipped_horizontal).save(output_file_horizontal)
Image.fromarray(flipped_vertical).save(output_file_vertical)



In [11]:
# View the flipped images
Image.fromarray(flipped_horizontal).show(title='Flipped Horizontally')
Image.fromarray(flipped_vertical).show(title='Flipped Vertically')